---
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/softKit'
    username: root
    password: 12345678
  mail:
    host: smtp.gmail.com
    username: antonignua@gmail.com
    password: hacotwpassegojji
    port: 587
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true

  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        "globally_quoted_identifiers": true
        format_sql: true
        id:
          new_generator_mappings: false

app.nfs.path: "/Users/antonignatenko/Downloads/fileUploads"

server:
  port: 8085
  error:
    include-stacktrace: never
    include-exception: false
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 30000000
